#!/usr/bin/env node
/**
 * Upload game assets to Vercel Blob (preserve path under assets/).
 *
 * Requires: BLOB_READ_WRITE_TOKEN in the environment.
 * Get it from: Vercel → Storage → barsik-game-blob → .env.local
 *
 * Usage:
 *   BLOB_READ_WRITE_TOKEN=vercel_blob_rw_... node scripts/upload-blob.mjs
 */
import { put } from '@vercel/blob';
import { readdir, readFile, writeFile, stat } from 'node:fs/promises';
import { join, relative, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const ASSETS = join(ROOT, 'assets');
const TOKEN = process.env.BLOB_READ_WRITE_TOKEN;
const PUBLIC_BASE = 'https://hb9433cf4odxkztt.public.blob.vercel-storage.com';

if (!TOKEN) {
  console.error('Missing BLOB_READ_WRITE_TOKEN');
  process.exit(1);
}

const SKIP = new Set(['brand', 'downloads']);
const OK_EXT = new Set(['.png', '.jpg', '.jpeg', '.webp', '.svg', '.gif', '.mp3', '.ogg', '.wav', '.json']);

async function walk(dir, out = []) {
  for (const name of await readdir(dir)) {
    if (name.startsWith('.')) continue;
    const p = join(dir, name);
    const st = await stat(p);
    if (st.isDirectory()) {
      if (SKIP.has(name) && dir === ASSETS) continue;
      await walk(p, out);
    } else if (OK_EXT.has(extname(name).toLowerCase())) {
      out.push(p);
    }
  }
  return out;
}

const files = await walk(ASSETS);
console.log(`Uploading ${files.length} files to Blob...`);
let ok = 0;
for (const file of files) {
  const pathname = relative(ROOT, file).replaceAll('\\', '/'); // assets/...
  const body = await readFile(file);
  const { url } = await put(pathname, body, {
    access: 'public',
    token: TOKEN,
    addRandomSuffix: false,
    allowOverwrite: true,
    contentType: undefined,
  });
  ok++;
  if (ok % 25 === 0 || ok === files.length) console.log(`  ${ok}/${files.length} ${url}`);
}

const cfg = `// Auto-generated by scripts/upload-blob.mjs — optional CDN mirror
window.BLOB_ASSET_BASE = ${JSON.stringify(PUBLIC_BASE)};
`;
await writeFile(join(ROOT, 'js', 'blob-config.js'), cfg);
console.log(`Done. ${ok} files. Base: ${PUBLIC_BASE}`);
console.log('Include js/blob-config.js if you want CDN fallback later.');
